-- ============================================================================
-- Employee QR Assignment Finder — Supabase migration 001: initial schema
-- ============================================================================
-- Run this ONCE in the Supabase SQL Editor (Dashboard → SQL Editor → New
-- query → paste → Run) for your project. It has NOT been executed against
-- any live database by the assistant — no Supabase project credentials were
-- available at the time this file was written. Review it before running.
--
-- This file is idempotent-ish (uses IF NOT EXISTS / OR REPLACE / DROP ... IF
-- EXISTS) so re-running it after a partial failure is safe.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 0. Extensions
-- ----------------------------------------------------------------------------
-- Needed for crypt()/gen_salt() used by the admin-key check below (PHASE 5
-- design note). If this errors with a permissions issue, enable "pgcrypto"
-- via Supabase Dashboard → Database → Extensions instead, then re-run.
create extension if not exists pgcrypto;


-- ----------------------------------------------------------------------------
-- 1. employees — the shared source of truth (PHASE 3)
-- ----------------------------------------------------------------------------
create table if not exists public.employees (
  id                  bigint generated by default as identity primary key,
  employee_number     text not null unique,
  name                text not null,
  email               text null,
  mem_group           text not null,
  mem_priority_group  text not null,
  tables              text[] not null default '{}',
  excel_row           integer null,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

comment on table public.employees is
  'Shared employee assignment data (MEM Group / Priority Group / Tables). '
  'employee_number is the real business key the app looks up by — id is '
  'just a surrogate PK, never exposed to or relied on by the frontend.';

-- updated_at auto-maintenance (Postgres has no MySQL-style
-- "ON UPDATE CURRENT_TIMESTAMP", so this needs an explicit trigger).
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists employees_set_updated_at on public.employees;
create trigger employees_set_updated_at
  before update on public.employees
  for each row
  execute function public.set_updated_at();


-- ----------------------------------------------------------------------------
-- 2. Row Level Security (PHASE 5)
-- ----------------------------------------------------------------------------
-- Public/anon must NOT be able to SELECT/INSERT/UPDATE/DELETE the table
-- directly. Enabling RLS with zero policies already default-denies
-- everything to anon/authenticated via PostgREST — the explicit revokes
-- below are a second, belt-and-suspenders layer so this holds regardless of
-- any default schema-level grants a project may already have.
alter table public.employees enable row level security;

revoke all on public.employees from anon, authenticated;
-- No policies are created here on purpose: with RLS enabled and no
-- policies, anon/authenticated get zero direct rows. The ONLY sanctioned
-- read path is the lookup_employee_by_number() RPC below (a SECURITY
-- DEFINER function, which runs with the privileges of the function owner
-- and so can read the table internally even though the *caller* cannot).


-- ----------------------------------------------------------------------------
-- 3. Public lookup RPC (PHASE 4)
-- ----------------------------------------------------------------------------
-- Returns ONLY the columns the public assignment result needs. Email is
-- deliberately excluded from the return type entirely (not just omitted by
-- convention) — there is no column in the result the caller could even ask
-- for that would leak it.
--
-- Mirrors the exact matching behavior of the current client-side
-- employeeStore.findByNumber() (src/services/employeeStore.ts):
--   1. Exact match on employee_number, case-insensitive, leading "#" trimmed
--   2. Fallback: numeric-only comparison — exact, "ends with", or
--      integer-equal (handles leading-zero differences), same as the
--      existing empNumeric === / .endsWith / parseInt-equality checks.
create or replace function public.lookup_employee_by_number(p_employee_number text)
returns table (
  employee_number     text,
  name                text,
  mem_group           text,
  mem_priority_group  text,
  tables              text[],
  excel_row           integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_cleaned text;
  v_numeric text;
begin
  v_cleaned := upper(trim(leading '#' from trim(p_employee_number)));
  if v_cleaned = '' then
    return;
  end if;

  -- 1. Exact match
  return query
    select e.employee_number, e.name, e.mem_group, e.mem_priority_group, e.tables, e.excel_row
    from public.employees e
    where upper(e.employee_number) = v_cleaned
    limit 1;

  if found then
    return;
  end if;

  -- 2. Numeric-suffix / equivalence fallback
  v_numeric := regexp_replace(v_cleaned, '\D', '', 'g');
  if v_numeric <> '' then
    return query
      select e.employee_number, e.name, e.mem_group, e.mem_priority_group, e.tables, e.excel_row
      from public.employees e
      where regexp_replace(e.employee_number, '\D', '', 'g') = v_numeric
         or regexp_replace(e.employee_number, '\D', '', 'g') like ('%' || v_numeric)
         or (
              regexp_replace(e.employee_number, '\D', '', 'g') ~ '^[0-9]+$'
              and regexp_replace(e.employee_number, '\D', '', 'g')::numeric = v_numeric::numeric
            )
      limit 1;
  end if;
end;
$$;

grant execute on function public.lookup_employee_by_number(text) to anon, authenticated;


-- ----------------------------------------------------------------------------
-- 4. Admin-key gate for shared-dataset WRITES (PHASE 5 design note)
-- ----------------------------------------------------------------------------
-- IMPORTANT — read this before relying on it:
-- The current admin login (src/services/adminAuth.ts) is a hardcoded
-- frontend password check with no real server-side identity, and this
-- migration was explicitly told NOT to redesign admin authentication yet.
-- Because the browser only ever holds the PUBLIC anon key, Postgres/RLS has
-- no way to tell "the real admin" apart from "any visitor" on the anon key
-- alone — both are the exact same credential. Granting anon direct
-- INSERT/UPDATE/DELETE on employees would let ANY visitor write, which is
-- explicitly forbidden.
--
-- The safest minimal bridge (per the explicit instruction to use "the
-- safest minimal approach and clearly report the limitation rather than
-- exposing the database") is: writes go through SECURITY DEFINER RPCs that
-- additionally require the same admin passphrase already used by the
-- existing login screen, checked SERVER-SIDE via a hashed comparison. This
-- is not a real multi-user auth system — it is exactly as strong as
-- today's password gate, just enforced where it can't be bypassed via
-- DevTools instead of only in the browser. A real Supabase Auth-based
-- upgrade is still recommended as a follow-up (see the final report).
create table if not exists public.app_admin_keys (
  key_hash text primary key
);

comment on table public.app_admin_keys is
  'Hashed admin passphrases accepted by the admin_* write RPCs. Mirrors the '
  'same two accepted passwords as the existing frontend check in '
  'src/services/adminAuth.ts (admin2026 / admin123) so the login UX is '
  'completely unchanged. Rotate by deleting a row and inserting a new hash.';

insert into public.app_admin_keys (key_hash)
values
  (extensions.crypt('admin2026', gen_salt('bf'))),
  (extensions.crypt('admin123', gen_salt('bf')))
on conflict (key_hash) do nothing;

alter table public.app_admin_keys enable row level security;
revoke all on public.app_admin_keys from anon, authenticated;
-- No policies — this table is never read directly by any client, only
-- consulted internally by the SECURITY DEFINER functions below.

create or replace function public.is_valid_admin_key(p_key text)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.app_admin_keys
    where key_hash = extensions.crypt(coalesce(p_key, ''), key_hash)
  );
$$;
-- Not granted to anon directly — only called internally by admin_* below.


-- ----------------------------------------------------------------------------
-- 5. Admin RPCs — shared-dataset reads/writes for the Admin Dashboard and
--    XLSX import (PHASE 7 / 9 / 10). Each one re-checks the admin key.
-- ----------------------------------------------------------------------------

-- Full employee list, for the Admin Dashboard table. Admin is a trusted
-- context, so email is included here (unlike the public RPC above).
create or replace function public.admin_list_employees(p_admin_key text)
returns setof public.employees
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_valid_admin_key(p_admin_key) then
    raise exception 'Invalid admin credentials';
  end if;

  return query select * from public.employees order by created_at desc;
end;
$$;

grant execute on function public.admin_list_employees(text) to anon, authenticated;


-- Single add/update, keyed by employee_number. Pass
-- p_original_employee_number when editing an existing record whose number
-- itself may be changing; pass null when creating a brand-new record.
create or replace function public.admin_upsert_employee(
  p_admin_key                  text,
  p_original_employee_number   text,
  p_employee_number            text,
  p_name                       text,
  p_email                      text,
  p_mem_group                  text,
  p_mem_priority_group         text,
  p_tables                     text[],
  p_excel_row                  integer
)
returns public.employees
language plpgsql
security definer
set search_path = public
as $$
declare
  v_result public.employees;
begin
  if not public.is_valid_admin_key(p_admin_key) then
    raise exception 'Invalid admin credentials';
  end if;

  if p_employee_number is null or trim(p_employee_number) = '' then
    raise exception 'Employee number cannot be empty';
  end if;
  if p_name is null or trim(p_name) = '' then
    raise exception 'Name cannot be empty';
  end if;

  if p_original_employee_number is not null then
    update public.employees
    set employee_number = trim(p_employee_number),
        name = trim(p_name),
        email = nullif(trim(coalesce(p_email, '')), ''),
        mem_group = p_mem_group,
        mem_priority_group = p_mem_priority_group,
        tables = p_tables,
        excel_row = p_excel_row
    where employee_number = p_original_employee_number
    returning * into v_result;

    if not found then
      raise exception 'Employee number "%" not found', p_original_employee_number;
    end if;
  else
    insert into public.employees
      (employee_number, name, email, mem_group, mem_priority_group, tables, excel_row)
    values
      (trim(p_employee_number), trim(p_name), nullif(trim(coalesce(p_email, '')), ''),
       p_mem_group, p_mem_priority_group, p_tables, p_excel_row)
    returning * into v_result;
  end if;

  return v_result;
end;
$$;

grant execute on function public.admin_upsert_employee(
  text, text, text, text, text, text, text, text[], integer
) to anon, authenticated;


-- Delete by employee_number.
create or replace function public.admin_delete_employee(
  p_admin_key text,
  p_employee_number text
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_valid_admin_key(p_admin_key) then
    raise exception 'Invalid admin credentials';
  end if;

  delete from public.employees where employee_number = p_employee_number;
  return found;
end;
$$;

grant execute on function public.admin_delete_employee(text, text) to anon, authenticated;


-- Bulk XLSX import: upserts a whole batch in one statement (one implicit
-- transaction), so a mid-batch failure can't leave the table half-updated.
-- employee_number is the conflict key, exactly as instructed — duplicates
-- within the same call simply upsert to the same row (last one wins), and
-- the XLSX parser already filters out in-file duplicate employee_numbers
-- before this is ever called (see src/services/xlsxImportService.ts).
create or replace function public.admin_import_batch(
  p_admin_key text,
  p_employees jsonb
)
returns table (upserted_count integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  if not public.is_valid_admin_key(p_admin_key) then
    raise exception 'Invalid admin credentials';
  end if;

  with input_rows as (
    select
      (r->>'employee_number')::text as employee_number,
      (r->>'name')::text as name,
      nullif((r->>'email')::text, '') as email,
      (r->>'mem_group')::text as mem_group,
      (r->>'mem_priority_group')::text as mem_priority_group,
      coalesce(
        (select array_agg(t) from jsonb_array_elements_text(r->'tables') as t),
        '{}'::text[]
      ) as tables,
      nullif(r->>'excel_row', '')::integer as excel_row
    from jsonb_array_elements(p_employees) as r
    where coalesce(trim(r->>'employee_number'), '') <> ''
      and coalesce(trim(r->>'name'), '') <> ''
  ),
  upserted as (
    insert into public.employees
      (employee_number, name, email, mem_group, mem_priority_group, tables, excel_row)
    select employee_number, name, email, mem_group, mem_priority_group, tables, excel_row
    from input_rows
    on conflict (employee_number) do update
      set name = excluded.name,
          email = excluded.email,
          mem_group = excluded.mem_group,
          mem_priority_group = excluded.mem_priority_group,
          tables = excluded.tables,
          excel_row = excluded.excel_row
    returning 1
  )
  select count(*) into v_count from upserted;

  return query select v_count;
end;
$$;

grant execute on function public.admin_import_batch(text, jsonb) to anon, authenticated;
